model:
  B: 32  # Batch size
  T: 2   # Time steps
  V_s: 3 # Number of surface variables
  V_a: 5 # Number of atmospheric variables
  C: 13  # Number of atmospheric levels
  H: 32  # Height
  W: 64  # Width
  embed_dim: 512
  num_latent_tokens: 4

data:
  atmos_levels: [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50]

training:
  batch_size: 1
  workers: 4
  epochs: 20
  accelerator: auto
  precision: bf16
  devices: 1
  gradient_clip: 1.0
  log_steps: 10

general:
  do_eval: True

mlflow:
  port: 5002 # change here port if you get [Errno 98] Address already in use
