model:
  B: 32  # Batch size
  T: 2   # Time steps
  V_surf: 2 # Number of surface variables
  V_atmos: 2 # Number of atmospheric variables
  C: 3  # Number of atmospheric levels
  V_spec: 1 # Number of extinct_species variables
  V_land: 2 # Number of land variables
  V_agri: 4 # Number of agriculture variables
  V_forest: 1 # Number of forest variables
  H: 32  # Height
  W: 64  # Width
  embed_dim: 512
  num_latent_tokens: 4
  patch_size: 4
  backbone: "swin" # mvit

data:
  atmos_levels: [50, 500, 1000]

training:
  batch_size: 1
  workers: 0
  epochs: 20
  accelerator: cuda
  precision: bf16-mixed
  devices: [1]
  strategy: fsdp # ddp
  gradient_clip: 1.0
  log_steps: 1

general:
  do_eval: True

mlflow:
  port: 5002 # change here port if you get [Errno 98] Address already in use
