model:
  T: 2   # Time steps
  V_surf: 2 # Number of surface variables
  V_atmos: 2 # Number of atmospheric variables
  C: 3  # Number of atmospheric levels
  V_spec: 1 # Number of extinct_species variables
  V_land: 2 # Number of land variables
  V_agri: 4 # Number of agriculture variables
  V_forest: 1 # Number of forest variables
  H: 152  # Height
  W: 320  # Width
  num_latent_tokens: 8 #TODO Check consistensy in name and value
  backbone: "swin" # mvit
  patch_size: 4 # Size of spatial patches.
  embed_dim: 512 # Embedding dimension.
  num_heads: 16 # Number of attention heads.
  head_dim: 64 # Dimension of each attention head.
  depth: 2 # Number of transformer layers.

data:
  atmos_levels: [50, 500, 1000]
  species_number: 4 # [0-22] available species
  data_path: /projects/prjs1134/data/projects/biodt/storage/batches_2025_02_17/ #data_small/batches /projects/prjs1134/data/projects/biodt/storage/batches_2024_12_13 #/projects/prjs1134/data/projects/biodt/storage/batches_2025_01_22/train  #/projects/prjs1134/data/projects/biodt/storage/batches_2025_01_22/train #/projects/prjs1134/data/projects/biodt/storage/batches_2024_12_13 #data/ #/projects/prjs1134/data/projects/biodt/storage/batches/
  test_data_path: data_small/batches/
#TODO Checkpointing path: /scratch-shared/<username>
 
training:
  batch_size: 4
  workers: 15
  epochs: 2
  accelerator: gpu
  precision: bf16-mixed
  precision_in: "medium" # ["high", "highest"] https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
  devices: [0]
  strategy: fsdp #fsdp #ddp
  num_nodes: 1
  gradient_clip: 1.0
  log_steps: 1
  lr: 0.0005  #5e-4
  wd: 0.000005 #5e-6
  checkpoint_path: False

general:
  do_eval: True

mlflow:
  port: 8082 # change here port if you get [Errno 98] Address already in use

evaluation:
  checkpoint_path: /home/atrantas/bfm-model/outputs/2025-02-19/11-46-40/checkpoints/epoch=1-step=140.ckpt #outputs/2025-02-17/15-36-49/checkpoints/epoch=8-step=9.ckpt #/home/atrantas/bfm-model/outputs/2025-02-12-withcheckpoint/16-04-11/checkpoints/epoch=0-step=26.ckpt
  batch_size: 4
  test_device: "cuda:0"